
services:
  postgres-db:
    image: postgres:16-alpine
    container_name: lafam_postgres
    restart: always
    environment:
      POSTGRES_USER: premeees
      POSTGRES_PASSWORD: 972547
      POSTGRES_DB: lafam_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U premeees -d lafam_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: lafam_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: peam972547@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 972547
    ports:
      - "5050:80"
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  pgdata:
